### ISSUE TITLE
Tab Info Content does not change

### ISSUE THREAD

**Issue by cyfung1031** [tabview-youtube/Tabview-Youtube#46]
https://greasyfork.org/en/scripts/428651-tabview-youtube/discussions/250259

**Comment by Dark3n89** [comment]
Lol this never work, never inside any version of code friend.  ( chrome multiple version )
I do new window or reloade 99% times.

**Comment by cyfung1031** [comment]
> Lol this never work, never inside any version of code friend. ( chrome multiple version ) I do new window or reloade 99% times.

Never work???

I think the issue should occur since the YouTube UI changed to this.
<img width="1015" alt="Screen Shot 2024-07-12 at 9 42 15" src="https://github.com/user-attachments/assets/9c558b49-437f-4312-9473-bcc064af4515">

The info update together with the video change was not working before that ??

**Comment by Dark3n89** [comment]
Yes, for me never. Work only for new window. Nonstom must reloade, tab.

Dne pá 12. 7. 2024 2:43 uživatel cyfung1031 ***@***.***>
napsal:

**Comment by cyfung1031** [comment]
But the video title below the video would refresh right?

What is your browser?

**Comment by cyfung1031** [comment]
@Dark3n89 

But the video title below the video would refresh right?

What is your browser?

-----------------------------

Can you try this to see whether tab info content will update along with the video page changing?

(this is just a testing version)

[wh3fs.user.js.zip](https://github.com/user-attachments/files/16263841/wh3fs.user.js.zip)

**Comment by cyfung1031** [comment]
I did not receive your reply to confirm the issue.

Anyway, the reconstructed version will be located in https://github.com/tabview-youtube/Tabview-YouTube-Totara

This repo will become a legacy version
