### ISSUE TITLE
BUG SOLVED:  Google kid scam :)  Downgrade your version for temporary fix

### ISSUE THREAD

**Issue by Dark3n89** [tabview-youtube/Tabview-Youtube#48]
I have all old versions of all my favorite userscripts.

DOWNGRADE TO VERSION: 4.73.17 ♥

![image](https://github.com/user-attachments/assets/7d1f37af-3bfa-4df0-b601-38d8c384b112)

**Comment by cyfung1031** [comment]
The latest version ( v4.73.27) should work. Please update the status.
