### ISSUE TITLE
Tabview youtube no longer works!!!!

### ISSUE THREAD

**Issue by hitmonray** [tabview-youtube/Tabview-Youtube#49]
Expected Behavior
tabview youtube used to work (live chat, comments, etc all in tabs to the right of video)

Actual Behavior
complete failure of youtube as a whole as of 2 days ago. Works after disabling tampermonkey

Pages barely load if it all. Video might play for a second then stop. Chat / comments never load.

started happening randomly 2 days ago. disabling tampermonkey everything works normal.

tabview youtube is the only tampermonkey script enabled.

using brave browser on windows

Specifications
Chromium: brave browser1.68.141
windows

Script
default Tabview youtube script too long to post here

**Comment by Dark3n89** [comment]
Downgrade to version 4.73.17 and shut up xD
No need Thanks :)

**Comment by hitmonray** [comment]
> Downgrade to version 4.73.17 and shut up xD No need Thanks :)

do u have a link? this website sucks can't find where to download shit or any of the scripts or anything. this website needs a serious redesign

**Comment by hitmonray** [comment]
nevermind i found it on this website

https://greasyfork.org/en/scripts/428651-tabview-youtube?version=1407910

here's a link for anyone searching for 4.73.17

anybody reading this github needs to be seriosly redesigned and made user friendly as right now it is nearly unusable

**Comment by Dark3n89** [comment]
> nevermind i found it on this website
> 
> https://greasyfork.org/en/scripts/428651-tabview-youtube?version=1407910
> 
> here's a link for anyone searching for 4.73.17
> 
> anybody reading this github needs to be seriosly redesigned and made user friendly as right now it is nearly unusable

Here is working version:

https://greasyfork.org/en/scripts/428651-tabview-youtube?version=1407910

DELETE COOKIES!

**Comment by cyfung1031** [comment]
The latest version (	v4.73.27) should work. Please update the status.

**Comment by hitmonray** [comment]
with the recent brave update no longer the .17 nor the newest .27 are working. more work is needed urgently

**Comment by cyfung1031** [comment]
> with the recent brave update no longer the .17 nor the newest .27 are working. more work is needed urgently

Please describe more. 

- How to reproduce?
- Describe what features are not working.
- Only Brave? did you try other browsers?
- Happens on Logged in ? Happens on Logged out?
- Can you try https://greasyfork.org/en/scripts/501249-tabview-youtube-totara as well? Work or not?

**Comment by cyfung1031** [comment]
It seems that it is a separate issue. Moved to https://github.com/tabview-youtube/Tabview-Youtube/issues/51
