### ISSUE TITLE
Video description not updating

### ISSUE THREAD

**Issue by JER-ry** [tabview-youtube/Tabview-Youtube#52]
Content in the description tab will not update to the next video's (next item in the queue / in the recommendations / switch to popup then enter another video), unless refreshing the whole page.

Windows 11, Violentmonkey 2.26.0, Firefox & Edge

**Comment by cyfung1031** [comment]
This is the known issue. There is something unsolvable in this script. I am making a new version of Tabview Youtube.

Check it out at https://greasyfork.org/scripts/501249-tabview-youtube-totara/
