### ISSUE TITLE
The script is very useful. It would be even better if it had these two functions

### ISSUE THREAD

**Issue by zghb0517** [tabview-youtube/Tabview-Youtube#54]
Dear author,

I really appreciate your script. It has made my experience of using YouTube much more concise, natural and convenient. During the process of using it, I noticed that for many long comments, I have to click on them one by one to view the full content. It would be even better if the comments could be automatically expanded. Also, the navigation bar for comments is relatively too wide. It would be wonderful if its width could be adjusted.

Thank you again for your great work!
![QQ20241130-221624](https://github.com/user-attachments/assets/395089b7-ab9b-4a62-a88f-3045c74500c5)
![QQ20241130-221549](https://github.com/user-attachments/assets/e0e43fd1-c7e8-4064-84db-8b96805271a6)

**Comment by cyfung1031** [comment]
> It would be even better if the comments could be automatically expanded.
Disagree. This feature will never happen in this extension.



> the navigation bar for comments is relatively too wide. 

The width is appropriated. No Change
